# Generated by Django 5.1 on 2026-02-16 20:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0004_servicecategory_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='pic',
            field=models.ImageField(blank=True, default='img/service_default.png', upload_to='img/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg'))], verbose_name='Изображение'),
        ),
    ]
