# Generated by Django 5.1 on 2026-02-16 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0005_service_pic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'ordering': ['order'], 'verbose_name': 'Категория услуг', 'verbose_name_plural': 'Категории услуг'},
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='anchor',
            field=models.CharField(default='ser', max_length=20, verbose_name='id-якорь'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Порядок расположения'),
            preserve_default=False,
        ),
    ]
