# Generated by Django 5.1 on 2026-02-16 22:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0006_alter_servicecategory_options_servicecategory_anchor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.TextField(max_length=50, verbose_name='href')),
                ('alt', models.TextField(max_length=50, verbose_name='alt')),
                ('text', models.TextField(max_length=50, verbose_name='text')),
                ('order', models.IntegerField(verbose_name='Порядок расположения')),
                ('pic', models.ImageField(blank=True, default='img/contact_default.png', upload_to='img/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg'))], verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
                'ordering': ['order'],
            },
        ),
    ]
