# Generated by Django 5.1 on 2026-02-16 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0007_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='alt',
            field=models.CharField(max_length=50, verbose_name='alt'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='href',
            field=models.CharField(max_length=50, verbose_name='href'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='text',
            field=models.CharField(max_length=50, verbose_name='text'),
        ),
    ]
