# Generated by Django 5.1 on 2026-02-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0008_alter_contact_alt_alter_contact_href_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='content',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='email',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='subject',
        ),
        migrations.AddField(
            model_name='feedback',
            name='message',
            field=models.TextField(default='', max_length=1000, verbose_name='Сообщение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='name',
            field=models.CharField(default='q', max_length=30, verbose_name='Имя отправителя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='phone',
            field=models.CharField(default='12345678901', max_length=11, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
    ]
