# Generated by Django 5.1 on 2026-02-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0009_remove_feedback_content_remove_feedback_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metatag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Метатег')),
                ('content', models.TextField(blank=True, max_length=40, verbose_name='Содержание')),
            ],
            options={
                'verbose_name': 'Метатег',
                'verbose_name_plural': 'Метатеги',
                'ordering': ['name'],
            },
        ),
    ]
