# Generated by Django 5.1 on 2026-02-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0010_metatag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metatag',
            name='content',
            field=models.CharField(blank=True, max_length=200, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='metatag',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Метатег'),
        ),
    ]
