# Generated by Django 5.1 on 2026-02-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0011_alter_metatag_content_alter_metatag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metatag',
            name='content',
            field=models.CharField(blank=True, max_length=300, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='metatag',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Метатег'),
        ),
    ]
