# Generated by Django 5.1 on 2026-06-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0013_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Настройка'),
        ),
    ]
